encoding: UTF-8

theme: jekyll-theme-slate

author: "Fátima Garay"

lang: "es-ES"

permalink: date

title: [La mamá de Zoe]

description: [Aprendiendo todo de nuevo con mi hija]

paginate_path: "/blog/docs:num/"

pagination: 4
